import type { Metadata } from "next";
import Link from "next/link";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "AIMarketWire terms of service. Important disclaimers about AI-generated content and trading information.",
  alternates: {
    canonical: "https://aimarketwire.ai/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100">
      {/* Header */}
      <header className="sticky top-0 z-40 border-b border-zinc-800/80 bg-zinc-950/90 backdrop-blur-md">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-5 py-3.5">
          <Link href="/" className="font-mono text-lg font-bold tracking-tight">
            <span className="text-emerald-400">AI</span>
            <span className="text-zinc-100">MarketWire</span>
          </Link>
          <Link
            href="/"
            className="font-mono text-xs text-zinc-500 transition-colors hover:text-zinc-300"
          >
            {"\u2190"} Back to feed
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-5 py-12">
        <h1 className="mb-2 font-serif text-3xl font-medium text-zinc-50 md:text-4xl">
          Terms of Service
        </h1>
        <p className="mb-10 font-mono text-sm text-zinc-500">
          Last updated: 28 February 2026
        </p>

        <div className="space-y-8 text-base leading-relaxed text-zinc-300">
          <section>
            <h2 className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-emerald-500">
              Acceptance of Terms
            </h2>
            <p>
              By accessing and using AIMarketWire (aimarketwire.ai), you agree to be bound by
              these Terms of Service. If you do not agree with any part of these terms, you
              should not use the website.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-emerald-500">
              No Trading or Investment Advice
            </h2>
            <div className="rounded border border-amber-800/40 bg-amber-950/20 p-4">
              <p className="font-semibold text-amber-300">
                AIMarketWire does not provide trading advice, investment recommendations,
                financial guidance, or any form of professional financial advice.
              </p>
              <p className="mt-3 text-zinc-400">
                All content on this website — including article summaries, relevance scores,
                market impact analysis, ticker references, and category classifications — is
                generated by artificial intelligence for informational purposes only. Relevance
                scores indicate editorial relevance to AI markets, not investment merit or
                expected stock performance.
              </p>
              <p className="mt-3 text-zinc-400">
                You should not make any trading or investment decisions based solely on
                information provided by AIMarketWire. Always conduct your own research and
                consult a qualified, licensed financial adviser before making financial decisions.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-emerald-500">
              AI-Generated Content
            </h2>
            <p>
              Content on AIMarketWire is generated by artificial intelligence systems. While
              we strive for accuracy, AI-generated summaries and analysis may contain errors,
              omissions, or misinterpretations of source material. We make no warranties
              regarding the accuracy, completeness, or timeliness of AI-generated content.
            </p>
            <p className="mt-3">
              All article summaries are derived from publicly available news articles. We
              always link to the original source article. You should refer to original sources
              for complete and authoritative reporting.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-emerald-500">
              Source Attribution
            </h2>
            <p>
              AIMarketWire aggregates and summarises news from third-party sources. All original
              reporting is credited to its respective publisher. We provide direct links to
              original articles for attribution and verification. AIMarketWire does not claim
              ownership of original reporting.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-emerald-500">
              Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, AIMarketWire and its operators shall not
              be liable for any direct, indirect, incidental, consequential, or punitive damages
              arising from your use of the website or reliance on any content provided. This
              includes, without limitation, any financial losses resulting from trading or
              investment decisions.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-emerald-500">
              Intellectual Property
            </h2>
            <p>
              The AIMarketWire brand, logo, website design, and AI-generated analysis are the
              property of their respective owners. Original news content remains the intellectual
              property of its original publishers. You may share links to AIMarketWire pages but
              may not reproduce content in bulk without permission.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-emerald-500">
              Availability
            </h2>
            <p>
              We do not guarantee uninterrupted availability of the website. The service may
              be temporarily unavailable due to maintenance, updates, or circumstances beyond
              our control. We reserve the right to modify or discontinue the service at any time.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-emerald-500">
              Governing Law
            </h2>
            <p>
              These Terms of Service are governed by the laws of New South Wales, Australia.
              Any disputes arising from these terms shall be subject to the exclusive
              jurisdiction of the courts of New South Wales.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-emerald-500">
              Changes to Terms
            </h2>
            <p>
              We may update these Terms of Service at any time. Changes will be posted on this
              page with an updated date. Continued use of the website after changes are posted
              constitutes acceptance of the updated terms.
            </p>
          </section>
        </div>
      </main>

      <Footer maxWidth="3xl" activePath="/terms" />
    </div>
  );
}
